### PR TITLE
add sqllite x64,x68 lib

### LINKED ISSUE #24: Sqllite missing when export project as executable file
Project error when installing due to missling sqllite lib

### PR DESCRIPTION
**Pull request by pragasitcha**
Fix #24 

Test Result 

image

[INV02_cancel.pdf](https://github.com/ETDA/e-TaxInvoice-PDFgen/files/2067749/INV02_cancel.pdf)
[DBN01.pdf](https://github.com/ETDA/e-TaxInvoice-PDFgen/files/2067751/DBN01.pdf)
[INV01.pdf](https://github.com/ETDA/e-TaxInvoice-PDFgen/files/2067752/INV01.pdf)

### CODE REVIEW

**Review by nathamETDA — CHANGES_REQUESTED** [review]
ApplicationVersion in csproj file is not correct (1.0.0.1).
Please put the correct value (1.0.0.3)

**Comment by pragasitcha** [comment]
@nathamETDA  

change version to 1.0.3 krub

**Review by nathamETDA — APPROVED** [review]

**Comment by nathamETDA** [comment]
Version corrected, LGMT.

**Comment by pragasitcha** [comment]
merge Done krub

**Pull request merged**
