### PR TITLE
Integrate with api

### LINKED ISSUE #2: Use NuGet to reference iTextSharp
So that we can remove another binary in
e-TaxInvoice-PDFgen/eTaxInvoicePdfGenerator/libsITEXT/

https://www.nuget.org/packages/iTextSharp/

### LINKED ISSUE #8: Extract XML generation logic into its own repo and publish a public NuGet package
This will have many benefits to both the project and the community

1. People who have their own PDF / Invoice generation program would only be interested only in the xml generation logic
2. It's easier to add test and understand the code. The generation method also needs fix on edge cases along with many other unimplemented cases.
3. Possible to use this as a reference implementation to the spec. 

Specifically I'm talking about the code around this part

https://github.com/ETDA/e-TaxInvoice-PDFgen/blob/master/eTaxInvoicePdfGenerator/util/getInvoice_Xml.cs

https://github.com/ETDA/e-TaxInvoice-PDFgen/blob/master/eTaxInvoicePdfGenerator/PDFA3/ElectronicDocument.cs

### LINKED ISSUE #9: System.Data.SqlLite is missing from dependency
Got error above error in installation process. This can be fixed by
`Install-Package System.Data.SqLite`
However, we should push this to nuget reference and restore it automatically.

### PR DESCRIPTION
**Pull request by mahasak**
- Change to target .Net Framework 4.6.1 to support .Net standard library 2.0
- Add API reference to nuget package ETDA.Invoice.Api version 0.1.7
- Change XML Generation to API DLL
- Remove binary from git
- Remove some unused classes
- fix #2 
- fix #9 
- close #8

### CODE REVIEW

**Comment by varokas** [comment]
Reviewed. It seems like there's a bunch of entity framework config added. Intentional?

**Comment by varokas** [comment]
Protip @mahasak, if you link to issues using magic keyword. It will close when this PR is merged. 

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by mahasak** [comment]
@varokas It's already use System.Data.SQLite that import EF automatically, i just reference it to nuget correctly to make it automatically restore package on build. The master repo is missing this in package.config

**Comment by varokas** [comment]
I understand the SQLite NuGet package part. I don't know why it has a bunch of other entity framework configuration added, especially the SQLServer part. Please review the few lines I tagged and see if those are necessary.

**Comment by mahasak** [comment]
I think it's import by default by System.Data.SQLite.EF6. Anyway, I did not add any thing related to sqlserver in to project. Will try to remove it and test it E2E.

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.0.0" targetFramework="net40" requireReinstallation="true" />
  <package id="ETDA.Invoice.Api" version="0.1.7" targetFramework="net461" />
  <package id="iTextSharp" version="5.5.11" targetFramework="net40" />
  <package id="itextsharp.pdfa" version="5.5.11" targetFramework="net40" />
  <package id="itextsharp.xtra" version="5.5.11" targetFramework="net40" />
  <package id="Microsoft.ReportViewer.Common" version="10.0.40219.1" targetFramework="net461" />
  <package id="Microsoft.ReportViewer.WinForms" version="10.0.40219.1" targetFramework="net40" />
  <package id="System.Data.SQLite" version="1.0.105.2" targetFramework="net40" />
  <package id="System.Data.SQLite.Core" version="1.0.105.2" targetFramework="net40" requireReinstallation="true" />
  <package id="System.Data.SQLite.EF6" version="1.0.105.2" targetFramework="net40" requireReinstallation="true" />
  <package id="System.Data.SQLite.Linq" version="1.0.105.2" targetFramework="net40" requireReinstallation="true" />
</packages>
```

**Comment by mahasak** [comment]
@varokas It's really comes from reference of SQLite nuget package, and it's not used just removed it and tested.

**Comment by aixasz** [comment]
I think we could update dependencies reference url in `README.md`.

**Comment by mahasak** [comment]
@aixasz Thanks Nok, i had update dependency as you recommended !!!

**Comment by mahasak** [comment]
closed by @ExUltima commented

**Comment by varokas** [comment]
Also to make this work long term. Please review #15. Obviously we want ETDA to host the API and the NuGet package release so that people can contribute easier.

**Comment by varokas** [comment]
@pragasitcha  - if you don't understand this proposal. please chat me on Facebook I can explain the details.

**Comment by ultimaweapon** [comment]
ควรคุยกันในนี้น่าจะดีกว่านะครับ คนอื่นจะได้เข้าใจด้วย

**Comment by mahasak** [comment]
Close due to meeting note at ETDA

**Pull request closed without merging**
