### PR TITLE
Add Build Status

### PR DESCRIPTION
**Pull request by mahasak**
Add a build status from AppVayor to Readme.md page

sample of build status : https://github.com/mahasak/e-TaxInvoice-PDFgen/tree/appveyor (but badge is point to master project)

### CODE REVIEW

**Comment by varokas** [comment]
Appveyor does not have a config as a file? If yes, checks in the file somewhere in this project. Otherwise, LGTM

**Comment by mahasak** [comment]
We use server side config for now, I will export it once we get propert packaging procedure.

**Comment by varokas** [comment]
Fine with that

**Comment by mahasak** [comment]
BTW, i add it anyway.

**Review by varokas — APPROVED** [review]

**Pull request merged**
